
name: Windows CMake Build and Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4  # 更新至最新版本
    
    - name: Setup MSVC 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vs-version: '17.0'  # 明确指定VS2022版本^1^
    
    - name: Install CMake
      uses: lukka/get-cmake@v3.27  # 指定CMake稳定版本^2^
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -A x64  # 明确指定x64架构^3^
        
    - name: Build Release
      working-directory: ./
      run: cmake --build .. --config Release --parallel 4  # 启用并行编译^4^
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary_package
        path: |
          ./Release/*.exe
          ./Release/*.dll  # 包含可能的动态库^5^
