
name: Windows CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
    
    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
      
    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: build/Release/*.exe
